spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db_dev

logging:
  level:
    com.payment: DEBUG
    org.hibernate.SQL: DEBUG